-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object exposing (..)


type Class
    = Class


type ClassOfDay
    = ClassOfDay


type ClassOfWeek
    = ClassOfWeek


type Room
    = Room


type User
    = User


type WeekAndTime
    = WeekAndTime
