-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Query exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


{-| clavisionにあいさつをする
-}
hello : SelectionSet String RootQuery
hello =
    Object.selectionForField "String" "hello" [] Decode.string


type alias UserRequiredArguments =
    { accessToken : String }


{-| ユーザーの情報を取得する

  - accessToken - アクセストークン

-}
user : UserRequiredArguments -> SelectionSet decodesTo Api.Object.User -> SelectionSet decodesTo RootQuery
user requiredArgs object_ =
    Object.selectionForCompositeField "user" [ Argument.required "accessToken" requiredArgs.accessToken Encode.string ] object_ identity


{-| すべての教室のデータ
-}
roomAll : SelectionSet decodesTo Api.Object.Room -> SelectionSet (List decodesTo) RootQuery
roomAll object_ =
    Object.selectionForCompositeField "roomAll" [] object_ (identity >> Decode.list)


{-| すべての授業のデータ
-}
classAll : SelectionSet decodesTo Api.Object.Class -> SelectionSet (List decodesTo) RootQuery
classAll object_ =
    Object.selectionForCompositeField "classAll" [] object_ (identity >> Decode.list)
