-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.ScalarCodecs exposing (..)

import Api.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias Url =
    Api.Scalar.Url


codecs : Api.Scalar.Codecs Url
codecs =
    Api.Scalar.defineCodecs
        { codecUrl = defaultCodecs.codecUrl
        }
