-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.ScalarCodecs exposing (..)

import Api.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias FileHash =
    Api.Scalar.FileHash


type alias Url =
    Api.Scalar.Url


codecs : Api.Scalar.Codecs FileHash Url
codecs =
    Api.Scalar.defineCodecs
        { codecFileHash = defaultCodecs.codecFileHash
        , codecUrl = defaultCodecs.codecUrl
        }
