-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Class exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| 授業を識別するためのID
-}
id : SelectionSet String Api.Object.Class
id =
    Object.selectionForField "String" "id" [] Decode.string


{-| 授業名
-}
name : SelectionSet String Api.Object.Class
name =
    Object.selectionForField "String" "name" [] Decode.string


{-| 講師
-}
teacher : SelectionSet String Api.Object.Class
teacher =
    Object.selectionForField "String" "teacher" [] Decode.string


{-| 曜日と時限
-}
weekAndTime : SelectionSet decodesTo Api.Object.WeekAndTime -> SelectionSet decodesTo Api.Object.Class
weekAndTime object_ =
    Object.selectionForCompositeField "weekAndTime" [] object_ identity


{-| 教室
-}
room : SelectionSet decodesTo Api.Object.Room -> SelectionSet decodesTo Api.Object.Class
room object_ =
    Object.selectionForCompositeField "room" [] object_ identity
