-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.ClassOfDay exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| 1限目の授業。nullは未登録が空きコマ
-}
class1 : SelectionSet decodesTo Api.Object.Class -> SelectionSet (Maybe decodesTo) Api.Object.ClassOfDay
class1 object_ =
    Object.selectionForCompositeField "class1" [] object_ (identity >> Decode.nullable)


{-| 2限目の授業。nullは未登録が空きコマ
-}
class2 : SelectionSet decodesTo Api.Object.Class -> SelectionSet (Maybe decodesTo) Api.Object.ClassOfDay
class2 object_ =
    Object.selectionForCompositeField "class2" [] object_ (identity >> Decode.nullable)


{-| 3限目の授業。nullは未登録が空きコマ
-}
class3 : SelectionSet decodesTo Api.Object.Class -> SelectionSet (Maybe decodesTo) Api.Object.ClassOfDay
class3 object_ =
    Object.selectionForCompositeField "class3" [] object_ (identity >> Decode.nullable)


{-| 4限目の授業。nullは未登録が空きコマ
-}
class4 : SelectionSet decodesTo Api.Object.Class -> SelectionSet (Maybe decodesTo) Api.Object.ClassOfDay
class4 object_ =
    Object.selectionForCompositeField "class4" [] object_ (identity >> Decode.nullable)


{-| 5限目の授業。nullは未登録が空きコマ
-}
class5 : SelectionSet decodesTo Api.Object.Class -> SelectionSet (Maybe decodesTo) Api.Object.ClassOfDay
class5 object_ =
    Object.selectionForCompositeField "class5" [] object_ (identity >> Decode.nullable)
