-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.ClassOfWeek exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| 月曜日の授業
-}
monday : SelectionSet decodesTo Api.Object.ClassOfDay -> SelectionSet decodesTo Api.Object.ClassOfWeek
monday object_ =
    Object.selectionForCompositeField "monday" [] object_ identity


{-| 火曜日の授業
-}
tuesday : SelectionSet decodesTo Api.Object.ClassOfDay -> SelectionSet decodesTo Api.Object.ClassOfWeek
tuesday object_ =
    Object.selectionForCompositeField "tuesday" [] object_ identity


{-| 水曜日の授業
-}
wednesday : SelectionSet decodesTo Api.Object.ClassOfDay -> SelectionSet decodesTo Api.Object.ClassOfWeek
wednesday object_ =
    Object.selectionForCompositeField "wednesday" [] object_ identity


{-| 木曜日の授業
-}
thursday : SelectionSet decodesTo Api.Object.ClassOfDay -> SelectionSet decodesTo Api.Object.ClassOfWeek
thursday object_ =
    Object.selectionForCompositeField "thursday" [] object_ identity


{-| 金曜日の授業
-}
friday : SelectionSet decodesTo Api.Object.ClassOfDay -> SelectionSet decodesTo Api.Object.ClassOfWeek
friday object_ =
    Object.selectionForCompositeField "friday" [] object_ identity


{-| 土曜日の授業
-}
saturday : SelectionSet decodesTo Api.Object.ClassOfDay -> SelectionSet decodesTo Api.Object.ClassOfWeek
saturday object_ =
    Object.selectionForCompositeField "saturday" [] object_ identity
